version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db
      MYSQL_USER: brayan
      MYSQL_PASSWORD: brayan
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-prod:
    image: mysql:latest
    container_name: mysql-container-prod
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products-db
      MYSQL_USER: brayan-prod
      MYSQL_PASSWORD: brayan-prod
    ports:
      - "3308:3306"
    volumes:
      - mysql-prod-data:/var/lib/mysql

  postgres:
    image: postgres:16.1
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'orders-db'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: load-balancer
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: msg-broker
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      
  mongo-db:
    image: mongo:7.0.5-rc0
    restart: always
    container_name: mongo-db
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: sa
      MONGO_INITDB_DATABASE: orders
    ports:
      - "27017:27017"


volumes:
  mysql-prod-data:
  mysql-data:
  pgdata:
