spring:
  profiles:
    default: default
  application:
    name: ms-api-gateway

server:
  port: 4040
  
eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    instance-id: '${spring.application.name}:${random.value}'
